target 'NASAApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NASAAPP
pod 'Alamofire', '~> 4.8'
pod 'AlamofireImage', '~> 3.5'

target 'NASAAppTests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
  end 



end
